title: Marijuana Anonymous District 6 - North Los Angeles
description: Jekyll theme for a conference website
baseurl: /mad6web
url: https://stream-enterer.github.io

permalink: pretty

home: /
copyright: MA District 6
indexing: true

exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
  
